OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
WPM_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = no
TAP_DANCE_ENABLE = no
SPLIT_KEYBOARD = yes

LTO_ENABLE = yes
